// zgt-react/src/components/YaMap.js
import React, { useEffect, useState } from 'react';
import "./YaMap.css";
export default function YaMap(props) {
    const { className, city } = props;
    const [myMap, setMyMap] = useState(null);
    const [myPlacemark, setMyPlacemark] = useState(null);
    const [ymaps, setYmaps] = useState(window.ymaps);

    const handler = () => { 
        if (city !== null && city !==undefined && myMap !== null){
            console.log(city);
            var coords = city.coords.match(/(\d{1,2}\.\d{1,4})/g);
            myMap.setCenter(coords, 7, {
                checkZoomRange: true
            });
            var myPlacemark = new ymaps.Placemark(coords, {
                balloonContentHeader: "Офис",
                balloonContentBody: `${city.name}`,
                balloonContentFooter: `${city.phone}`,
                hintContent: `Офис ${city.name}`
            })
            myMap.geoObjects.add(myPlacemark)
        }
    }
    useEffect(() => {
        ymaps.ready(() => {
            var coords = city === null || city === undefined ? [55.7558, 37.6173] : city.coords.match(/(\d{1,2}\.\d{1,4})/g);
            console.log(city)
            setMyMap(new ymaps.Map("ym-map", {
                center: coords,
                zoom: 7
            }));
            if (city !== null && city !==undefined && myMap !== null) {
                setMyPlacemark(new ymaps.Placemark(coords, {
                    balloonContentHeader: "Офис",
                    balloonContentBody: `${city.name}`,
                    balloonContentFooter: `${city.phone}`,
                    hintContent: `Офис ${city.name}`
                }))
                myMap.geoObjects.add(myPlacemark);
            }
        })
        return () => {
        }
    }, [])
    useEffect(() => {
        if (city !== null && city !==undefined && myMap !== null)
            handler()
    }, [city, myMap])
    return (
        <div id="ym-map" className={className}>
        </div>
    );
}

// vue/clie/src/components/YaMap.vue
<template>
    <div id="ym-map" :class="className" :style="cssStyle"></div>
</template>
<style scoped>
#ym-map {
    display: block;
    max-width: 100%;
    height: 500px;
}
@media only screen and (max-width: 768px) {
    #ym-map {
    display: block;
    max-width: 95%;
    height: 200px;
}
}
</style>
<script>
var myMap = null;
var myPlacemark = null;
export default {
    props: {
        className: {
            required: false,
            type: String
        },
        width: {
            required: false,
            type: String
        },
        height: {
            required: false,
            type: String
        },
        cssStyle: {
            required: false,
            type: String
        },
        coords: {
            required: false,
            default() {
                return [37.64, 55.761]
            },
            type: Array
        },
        city: {
            required: false,
            default() {
                return null
            },
            type: Object
        },
        
    },
    watch: { 
        city: {
            immediate: true,
            deep: true,
            handler(newVal, oldVal) { // watch it
                console.log(111, newVal, myMap);
                if (newVal !== null && myMap !== null){
                    var coords = newVal.coords.match(/(\d{1,2}\.\d{1,4})/g);
                    myMap.setCenter(coords, 7, {
                        checkZoomRange: true
                    });
                    myPlacemark = new ymaps.Placemark(coords, {
                        balloonContentHeader: "Офис",
                        balloonContentBody: `${newVal.name}`,
                        balloonContentFooter: `${newVal.phone}`,
                        hintContent: `Офис ${newVal.name}`
                    });
                    myMap.geoObjects.add(myPlacemark);
                }
            }
        }
    },
    methods: {
        init() {
            console.log(777);
            var coords = this.city === null ? [55.7558, 37.6173] : this.city.coords.match(/(\d{1,2}\.\d{1,4})/g);
            myMap = new ymaps.Map("ym-map", {
                center: coords,
                zoom: 7
            });
            if (this.city !== null) {
                myPlacemark = new ymaps.Placemark(coords, {
                    balloonContentHeader: "Офис",
                    balloonContentBody: `${this.city.name}`,
                    balloonContentFooter: `${this.city.phone}`,
                    hintContent: `Офис ${this.city.name}`
                });
                myMap.geoObjects.add(myPlacemark);
            }
        },
    },
    created() {
        ymaps.ready(this.init);
    },
}
</script>
